### ISSUE TITLE
app.js 要填入的 div 確認， html tag 要符合 id 格式，才會驅動 product list, suggestion tag 的填入。

### ISSUE THREAD

**Issue by awoocaesar** [awootaiwan/nununi-sdk-js#10]
app.js 是一個起始的 function, 

要將對應的 div加上 id 之後，才會將 product list 進行注入。

預期，
```
<div id="cupid-product-list"></div>
```

就會將 product list 資料填入

```
<div id="cupid-suggestion-tag"></div>
```

就會將 suggestion tag 填入。

**Comment by annytseng** [comment]
@johnnyyu0930 怎麼用API拿到資料?

**Comment by annytseng** [comment]
@johnnyyu0930 怎麼把資料傳給 SuggestionTag，ProductList

**Comment by johnnyyu0930** [comment]
> @johnnyyu0930 怎麼用API拿到資料?
在app.js 裡面寫一個async function 去呼叫 @amyhsieh16  寫的api 可以問先問他api的function名稱
然後再到render 裡面呼叫async function 去取得資料

**Comment by johnnyyu0930** [comment]
> @johnnyyu0930 怎麼把資料傳給 SuggestionTag，ProductList

由上面回應的function 可以取得api資料
然後用類似
```
const { suggestionTags, ProductList } = data;
```
語法去取得你要傳遞的資料
用類似下面的語法傳遞資料
```
<ProductList products={ProductList} />
```

**Comment by annytseng** [comment]
@johnnyyu0930 好的，感謝

**Comment by annytseng** [comment]
@johnnyyu0930 目前app.js是引入 ProductList，suggestionTags 的component來呈現
現在要加上show errormsg，要怎麼在額外可以show出錯誤訊息

**Comment by johnnyyu0930** [comment]
> @johnnyyu0930 目前app.js是引入 ProductList，suggestionTags 的component來呈現
> 現在要加上show errormsg，要怎麼在額外可以show出錯誤訊息

你想表達的應該是目前render出去的component是直接render import進來的元件
我的解法是這樣 
在你現在的app.js 寫一個 component 例如
```
const App = (props) => (
  <React.fragment>
      <ErrorAlert msg = {props.errorMsg} />   //顯示error msg的元件
      {props.children}   //這邊就是下面的ProductList 元件
  </React.fragment>
)
```
下面render function 就這樣寫
```
ReactDOM.render(<App errorMsg={errorMsg}><ProductList/><App/>, App);
```

**Comment by johnnyyu0930** [comment]
init function token ,id 
如果使用者忘記填寫記得丟error
```
if (ID == '' || TOKEN == '') {
  throw new Error("error msg");
}
```

**Comment by annytseng** [comment]
> init function token ,id
> 如果使用者忘記填寫記得丟error
> 
> ```
> if (ID == '' || TOKEN == '') {
>   throw new Error("error msg");
> }
> ```

謝謝Johnny!

**Comment by awoocaesar** [comment]
再麻煩試一下 API 整合的部分。

**Comment by annytseng** [comment]
> 再麻煩試一下 API 整合的部分。

@awoocaesar 
已經測試好，並pr了！
再麻煩review，謝謝您
