### ISSUE TITLE
documentation for 範例 html

### ISSUE THREAD

**Issue by awoocaesar** [awootaiwan/nununi-sdk-js#11]
提供給客戶的範例 html , 需要可以讓客戶知道怎麼使用 html , cupid-js sdk, 同時也提供範例有 header , menu, footer 的架構，

詳細參考規格，可以參考此頁面，
https://www.s3.com.tw/product-list/?labels=%E9%9F%93%E5%9C%8B,%E6%B4%97%E9%9D%A2%E4%B9%B3

截圖如下，
![image.png](https://images.zenhubusercontent.com/5d03162d53c309453ad5d217/c1acc07c-939d-4227-988f-c78b8892ffa9)

**Comment by johnnyyu0930** [comment]
ref: https://github.com/awootaiwan/cupid-sdk-js/issues/16
