### ISSUE TITLE
 How to save init function's token and nununi id

### ISSUE THREAD

**Issue by johnnyyu0930** [awootaiwan/nununi-sdk-js#12]
使用者的token和 id 要存在哪裡讓api.js 存取

目前想到存在 localstorage

**Comment by awoocaesar** [comment]
可以採用這樣的方式來進行，

https://github.com/awootaiwan/cupid-sdk-js/issues#workspaces/awoo-workspace-5d0752dd693682482417e152/board

透過設定 variable 來進行 domain設定。

**Comment by awoocaesar** [comment]
至於 demo頁的部分，就可以先將 token, cupid id 寫上去到範例中，
當然 commit 的部分，建立先用假的

例如先 commit 上來 的內容如下，
```
api.post({'cupidid: 'xxxxxx'});
```

實際上自己在使用的時候，在本地端再將 xxxx 改掉即可。
不過這段設定的部分，就建議在 readme 中寫清楚要改哪段那個部分進行設定。
已方便後續文件的改寫～

**Comment by johnnyyu0930** [comment]
透過全域變數 解決了
