### ISSUE TITLE
README 的建立

### ISSUE THREAD

**Issue by awoocaesar** [awootaiwan/nununi-sdk-js#13]
將此專案如何建立，如何 build , 如何進行測試，如何進行模組安裝的說明設定上去

**Comment by johnnyyu0930** [comment]
env設定解說可以參考這個commit
https://github.com/awootaiwan/cupid-sdk-js/pull/17#issuecomment-503395348

**Comment by johnnyyu0930** [comment]
https://github.com/awootaiwan/cupid-sdk-js/pull/17
連同這個pull request 一起推上去了
