### ISSUE TITLE
靜態頁面的切版

### ISSUE THREAD

**Issue by mingyou1219** [awootaiwan/nununi-sdk-js#16]
Header,Footer,Menu建立框架,切版

**Comment by mingyou1219** [comment]
@awookamili 關於連結顏色怎麼從藍色變成白色還有請幫我看目前美觀哪裡需要更改

**Comment by awookamili** [comment]
> @awookamili 關於連結顏色怎麼從藍色變成白色還有請幫我看目前美觀哪裡需要更改

你使用的是a這個標籤,在瀏覽器上,對於這個標籤的預設：點擊前為藍色,點擊過後為紫色,在使用瀏覽器上多多少少有遇過連結預設顏色的情況,如果要完全把它變成白色,可以去Google一下<a>的標籤可以設哪些屬性,會使用到的應該是a:link以及a:visited.

**Comment by mingyou1219** [comment]
@awookamili 關於Caesar的要求,我需要將css轉成scss,所以請教如何將css轉成scss

**Comment by awookamili** [comment]
> @awookamili 關於Caesar的要求,我需要將css轉成scss,所以請教如何將css轉成scss

這部分我待會會協助你,先檢查你的code,每個元素都要好好對應它的上層,檢查完後我再幫你看.
