### ISSUE TITLE
 js sdk, wrap api connection

### ISSUE THREAD

**Issue by awoocaesar** [awootaiwan/nununi-sdk-js#6]
將 api 的連線設定，設定為採用 axios 進行 get /post 的項目，
可以接收相關參數

並且可以回傳相關失敗狀態。

**Comment by awoocaesar** [comment]
api 的部分，關於連線方式請參考，
https://github.com/awootaiwan/cupid-sdk-js/issues/5

**Comment by awoocaesar** [comment]
這邊提醒一下，關於 token , domain , cupid id 等項目，建議採用 env variable 的方式來進行
相關文件，

https://parceljs.org/env.html

**Comment by johnnyyu0930** [comment]
> 這邊提醒一下，關於 token , domain , cupid id 等項目，建議採用 env variable 的方式來進行
> 相關文件，
> 
> https://parceljs.org/env.html

將env檔案忽略
https://github.com/awootaiwan/cupid-sdk-js/pull/17

**Comment by amyhsieh16** [comment]
api 如何取得 init 裡的參數{id,token} ？

**Comment by johnnyyu0930** [comment]
> api 如何取得 init 裡的參數{id,token} ？

配合 @annytseng  的app.js檔案那邊用變數傳進去api裡面
![image](https://user-images.githubusercontent.com/47519561/59736496-748d3a00-928c-11e9-8ce3-8d2f65a24fc6.png)

**Comment by amyhsieh16** [comment]
@awoocaesar  無法串接api，目前會出現的error訊息 ↓

![image](https://user-images.githubusercontent.com/46662655/59745437-6567b580-92a7-11e9-9e2e-8cf437304434.png)

**Comment by awoocaesar** [comment]
@amyhsieh16  目前已經修正完成，再麻煩確認一下，能不能都再跟我說～感謝～

**Comment by amyhsieh16** [comment]
@awoocaesar 現在的錯誤畫面↓
![image](https://user-images.githubusercontent.com/46662655/59827160-86dda580-936a-11e9-8632-ef8df298f4e0.png)

**Comment by awoocaesar** [comment]
已經可以正常使用～

**Comment by amyhsieh16** [comment]
code已經修好了，已發pr
