### ISSUE TITLE
 js component for product

### ISSUE THREAD

**Issue by awoocaesar** [awootaiwan/nununi-sdk-js#7]
需要透過 react 建立每個 product 商品項目

每一個 product 的項目，就是一個方匡，會有對應的 component 以及對應專屬的 css 項目。

**Comment by awoocaesar** [comment]
必須要切開架構，提醒統一採用 react hook 寫法來進行。

**Comment by youlixiao** [comment]
@awoocaesar 
#20 
請幫忙preview

**Comment by youlixiao** [comment]
baseUrl${sort}=${sort[key]}
這個貼上去有錯

**Comment by johnnyyu0930** [comment]
> baseUrl${sort}=${sort[key]}
> 這個貼上去有錯

這邊應該是這樣
```
 `${baseUrl}sort=${sort[key]}`
```
