### ISSUE TITLE
js component for suggestion tag

### ISSUE THREAD

**Issue by awoocaesar** [awootaiwan/nununi-sdk-js#8]
回傳 api 內容當中會有 suggestion tag ，
將回傳 tag 內容，變為 tag 元件，可以正確顯示，

顯示示意圖為，
![image.png](https://images.zenhubusercontent.com/5d03162d53c309453ad5d217/54c3a82c-829a-4dc2-b90c-5776f7009a32)

要注意排列的模式，是採用類似 inline-block 的模式來進行顯示

**Comment by awoocaesar** [comment]
必須要切開架構，提醒統一採用 react hook 寫法來進行。

**Comment by awookamili** [comment]
https://github.com/awootaiwan/cupid-sdk-js/pull/19

@awoocaesar 幫忙Review

**Comment by awookamili** [comment]
@johnnyyu0930  關於切版上的問題,元素寬度上的設置基本100％就好嗎？還是可以寫死？

**Comment by johnnyyu0930** [comment]
> @johnnyyu0930 關於切版上的問題,元素寬度上的設置基本100％就好嗎？還是可以寫死？

這邊因為是要給第三方使用所以不可以把component的寬度定死
要讓第三方自己定義一個div去設定自己想要的width，所以設定100%就可以了

**Comment by awookamili** [comment]
> > @johnnyyu0930 關於切版上的問題,元素寬度上的設置基本100％就好嗎？還是可以寫死？
> 
> 這邊因為是要給第三方使用所以不可以把component的寬度定死
> 要讓第三方自己定義一個div去設定自己想要的width，所以設定100%就可以了

OK,了解.

**Comment by johnnyyu0930** [comment]
@awookamili 
要注意～ 你的suggestion tags list 裡面的 tag要切出來一個component
