### ISSUE TITLE
documentation 使用的說明文件

### ISSUE THREAD

**Issue by awoocaesar** [awootaiwan/nununi-sdk-js#9]
需要提供可以說明文件，
可以採用markdown 寫完，將使用流程，步驟，透過截圖，加上 html , js 程式碼的架構提供給大家。

**Comment by johnnyyu0930** [comment]
env設定解說可以參考這個commit
https://github.com/awootaiwan/cupid-sdk-js/pull/17#issuecomment-503395348

**Comment by johnnyyu0930** [comment]
@awoocaesar  這個文件要放在demo 裡面嗎 還是外層
